name: .NET+Docker CI/CD

on:
  push:
    branches: [ "master", "develop", "main" ]
    paths-ignore:
      - 'README.md'
      - '*.md'

jobs:
  build:
    name: Unit and Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore backend/SpMega.Backend/SpMega.Backend.csproj
      - name: Build
        run: dotnet build --no-restore backend/SpMega.Backend/SpMega.Backend.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal backend/SpMega.Backend/SpMega.Backend.csproj

  compose:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: yawaflua
          password: ${{ env.GITHUB_TOKEN }}

      - name: Log in to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.yawaflua.tech
          username: yawaflua
          password: ${{ env.GITEA_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ghcr.io/yawaflua/spmega
            git.yawaflua.tech/yawaflua/spmega

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/SpMega.Backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}